[package]
name = "universe-debug"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "universe-debug"
path = "src/main.rs"
required-features = ["dev-shell"]

[features]
dev-shell = ["dep:egui", "dep:egui-wgpu"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
egui = { workspace = true, optional = true }
egui-wgpu = { workspace = true, optional = true }
mimalloc.workspace = true
tracing.workspace = true
universe-engine.workspace = true
