[package]
name = "universe-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "engine"
path = "src/lib.rs"

[features]
dev-shell = ["dep:bytemuck"]

[lints]
workspace = true

[dependencies]
bytemuck = { workspace = true, optional = true }
glam.workspace = true
libm.workspace = true
rand_core.workspace = true
rand_xoshiro.workspace = true
thiserror.workspace = true
tracing.workspace = true
xxhash-rust.workspace = true
